### ISSUE TITLE
.jsx not compiling

### ISSUE THREAD

**Issue by atorgfr** [mattmccray/react-brunch#9] opened 2015-03-14 06:50 UTC
Hi, 

i try to start building an app with react but with this project 
https://github.com/tomv564/react-brunch-with-bootstrap/blob/master/app/testcomponent.jsx
can't find a way to normally compile .jsx file.

i still have the jsx format in the app.js. Can't find why any idea ?

**Comment by bcowdery** [comment] 2015-03-18 19:04
We're seeing the same issue as well. Component .jsx files are not being converted to JavaScript prior to joining the main app.js file. This was working a few weeks ago (Feb 26th was our last good build according to the logs) and it suddenly broke. Could an errant NPM package update be the cause of this?

**Comment by marcolz** [comment] 2015-03-23 17:50
Same here.

**Comment by bcowdery** [comment] 2015-03-23 18:19
This issue appears to be fixed in the master branch. We're now building against the github repository instead of the NPM package as a workaround while we wait for a new version to be published.

package.json
```
"react-brunch": "git://github.com/mattmccray/react-brunch.git#708bdfbe43",
```

**Comment by bradobro** [comment] 2015-03-26 20:55
I PR'd a fix. You can try it like this:

`npm install --save git://github.com/bradobro/react-brunch#42800378fdc9bcdd64b8ab5c64c408ef0c6e21a8`

**Comment by mattmccray** [comment] 2015-03-26 21:11
This should be fixed with the latest merge/release, right?

Re-open this issue if you still have problems.

**Closed by mattmccray** 2015-03-26 21:11 UTC
